#!/usr/bin/sh

leftwm-command "UnloadTheme"

killall xfsettingsd
killall polkit-gnome-authentication-agent-1
# killall blueman-applet
killall dunst
killall picom
killall stalonetray
eww kill
killall easyeffects
