#!/usr/bin/sh

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

/usr/lib/polkit-kde-authentication-agent-1 &
/usr/lib/pam_kwallet_init &
balooctl6 enable &
nm-applet &
dunst &
picom &
~/.config/polybar/launch.sh &

feh --bg-fill "$HOME/Pictures/Wallpapers/yourwallpaperhere.png"

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# User XDG Autostart
# openrgb --profile "Catppuccin Peach" &
