#!/usr/bin/sh

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

xfsettingsd --sm-client-disable &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# blueman-applet & # seems to be launched automatically by xfsettingsd?
dunst &
picom &
stalonetray &

eww open bar
feh --bg-fill "/home/sam/Pictures/mihu-italo-monument enlarge.png"

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# User XDG Autostart
env GTK_THEME=Adwaita:dark GDK_SCALE=1 easyeffects --gapplication-service &
