#!/usr/bin/sh

lxpolkit &
blueman-applet &
dunst &
picom --experimental-backends &
killall sxhkd; sxhkd &
/home/sam/.config/polybar/launch.sh &

# System XDG Autostart
abrt-applet --gapplication-service &

# User XDG Autostart
/home/sam/gtk4-scaler.sh &
easyeffects --gapplication-service &
openrgb --profile "Sea Blue Dim" &

feh --bg-fill "/home/sam/Pictures/mihu-italo-monument enlarge.png"
xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         4
bspc config window_gap           8
bspc config top_padding          58

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  "#373B41"
bspc config focused_border_color "#FAB387"

bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
