#!/usr/bin/sh

lxpolkit &
blueman-applet &
picom --experimental-backends &
sxhkd &
/home/sam/.config/polybar/launch.sh &

# XDG Autostart
/home/sam/gtk4-scaler.sh &
easyeffects --gapplication-service &

feh --bg-fill "/home/sam/Pictures/mihu-italo-monument enlarge.png"
xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding          68

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
