[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "Iosevka Nerd Font"
style = "Medium"

[cursor.style]
shape = "Beam"

[terminal.shell]
args = ["-lc", "zellij attach --index 0 || zellij"]
program = "/bin/bash"

[window]
opacity = 0.95

[general]
import = ["/home/sam/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
